nodeLinker: node-modules

packageExtensions:
  babel-plugin-transform-flow-enums@*:
    dependencies:
      '@babel/core': ^7.0.0
  react-native@*:
    dependencies:
      '@babel/core': ^7.0.0
      '@babel/preset-env': ^7.1.6
  react-native-codegen@*:
    dependencies:
      '@babel/core': ^7.0.0
      '@babel/preset-env': ^7.1.6

yarnPath: .yarn/releases/yarn-3.6.3.cjs
